name: Release

on:
  push:
    tags: [ "v*.*.*" ]
    
permissions:
  contents: write

jobs:
  Release:
    strategy:
      matrix:
        include:
          - rid: win-x64
            runs-on: windows-latest
            archive-suffix: zip
            archive-cmd: zip -j
          - rid: linux-x64
            runs-on: ubuntu-latest
            archive-suffix: tar.gz
            archive-cmd: tar -czvf
    
    runs-on: ${{ matrix.runs-on }}
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Set version
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish StringSpy --no-restore --self-contained true --runtime ${{ matrix.rid }} /p:Version=${VERSION}

      - name: Create archive
        working-directory: StringSpy/bin/Release/net9.0/${{ matrix.rid }}/publish/
        run: ${{ matrix.archive-cmd }} stringspy-${VERSION}-${{ matrix.rid }}.${{ matrix.archive-suffix }} *

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            StringSpy/bin/Release/net9.0/${{ matrix.rid }}/publish/*.${{ matrix.archive-suffix }}